global:
  image:
    repository: "kicapman1x/load-generator"
otel:
  image:
    repository: "otel/opentelemetry-collector"
    tag: "latest"
  otlpReceiverEndpoint: "0.0.0.0:4317"
  otlpExporterEndpoint: "telegraf.han.gg:4317"
  replicas: 1
  otlpReceiverPort: 4317
  # otlpExporterPort: 4317
facialSvc:
  image:
    tag: "facial-service-rc2"
  replicas: 1
flightSvc:
  image:
    tag: "flight-service-rc2"
  replicas: 1
housekeep:
  image:
    tag: "housekeep-rc2"
  replicas: 1
passengerSvc:
  image:
    tag: "passenger-service-rc2"
  replicas: 1
satelliteInterface:
  image:
    tag: "satellite-interface-rc2"
  replicas: 1
satellite1:
  image:
    tag: "satellite1-rc2"
  replicas: 1
satellite2:
  image:
    tag: "satellite2-rc2"
  replicas: 1
satellite3:
  image:
    tag: "satellite3-rc2"
  replicas: 1
sourceDataInterface:
  image:
    tag: "source-data-interface-rc2"
  replicas: 1