global:
  image:
    repository: "kicapman1x/load-generator"
otel:
  image:
    repository: "otel/opentelemetry-collector"
    tag: "latest"
  otlpReceiverEndpoint: "0.0.0.0:4317"
  otlpExporterEndpoint: "0.0.0.0:9888"
  replicas: 1
  otlpReceiverPort: 4317
  otlpExporterPort: 9888
facialSvc:
  image:
    tag: "facial-service-rc1"
  replicas: 1
flightSvc:
  image:
    tag: "flight-service-rc1"
  replicas: 1
housekeep:
  image:
    tag: "housekeep-rc1"
  replicas: 1
passengerSvc:
  image:
    tag: "passenger-service-rc1"
  replicas: 1
satelliteInterface:
  image:
    tag: "satellite-interface-rc1"
  replicas: 1
satellite1:
  image:
    tag: "satellite1-rc1"
  replicas: 1
satellite2:
  image:
    tag: "satellite2-rc1"
  replicas: 1
satellite3:
  image:
    tag: "satellite3-rc1"
  replicas: 1
sourceDataInterface:
  image:
    tag: "source-data-interface-rc1"
  replicas: 1